language: python
python: '3.6'
branches:
  except: "/^v\\d/"
before_install: pip install babel
install: true
script: python setup.py compile_catalog
deploy:
- provider: script
  script: 'curl --fail --data "{ \"tag_name\": \"v$(python setup.py --version)\",
    \"target_commitish\": \"$TRAVIS_COMMIT\", \"name\": \"v$(python setup.py --version)\"
    }" --user bot50:$GITHUB_TOKEN https://api.github.com/repos/$TRAVIS_REPO_SLUG/releases'
  on:
    branch: main
- provider: pypi
  user: "$PYPI_USERNAME"
  password: "$PYPI_PASSWORD"
  on:
    branch: main
notifications:
  slack:
    secure: qmUeGAIrqT/qQw3rhGZ6yrYreqVUatAo6GzABHJDdqfGBEYqLR75b1REVSfr7V6z+0hiGFmq8DmrU5PAQ6p2h4nEpRHAZQloY9qtyaxo1iiGy59HDgG9ZPFmX4ljZ8nBmRJGAW20kbx6PeAWRWLO3Wojh6V8DiqX8+VgF636RT/JWuGPaZpsdW0P1pVot5KWrtKoXT9/haSBu+0C+joOXxhjTY/mjdPL8lwrgCleU/ajEUBgGUXvrK/HMMPmdh56mjmlLnL9F3pEXt/vvI5H10c1Ej6z8sgywjxB3+63jsB+BjuHcrOYGc5RMlpsXGgy1By1HDlCSqHxFz/W0i8I0MpWSdifB4x1nqAoZeRLTcQqQft09+n6LWNSOQYDyYSN0Rv/4O5kx89KOE6+pXcjZJcv6QtKq8SgH9AiS2aTBqeLXFfVaDBbb83CJGmD317LGtraLIrnc+GXZb40IES3BufOoQ03tu916gbvUP2OKUZGwf2oR14kQzKcl+S+GZwTaHJBgJbplOdsTwwW0aP5yc3WgksrAp1yVm7zuBNq8SNbECRtVdOGIukQ1wJcaIxE/HAabX6J7QKyAfPW6V6RnC1+pepcIfh/Mfx/j8pm8K7hRTIXpB6MMWrWe/0NsS3Oo7VQY95SZWJZPaNboyYMJQYMwLIu9vtE5BZezpbcL6c=
